/*
** EPITECH PROJECT, 2020
** PSU_ftrace_2019
** File description:
** ftrace
*/

#ifndef ftrace_LIST_H_
#define ftrace_LIST_H_

#include <sys/syscall.h>
#include <syscall.h>

#include "ftrace.h"

static system_function_t sys_function[] = {
    {SYS_read, INT, "read", {INT, STR, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_write, INT, "write", {INT, STR, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_open, INT, "open", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_close, INT, "close", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_stat, INT, "stat", {STR, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_fstat, INT, "fstat", {INT, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_lstat, INT, "lstat", {STR, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_poll, INT, "poll", {PTR, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_lseek, INT, "lseek", {INT, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_mmap, PTR, "mmap", {PTR, INT, INT, INT, INT, INT}, 6},
    {SYS_mprotect, INT, "mprotect", {PTR, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_munmap, INT, "munmap", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_brk, INT, "brk", {PTR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_rt_sigaction, INT, "rt_sigaction", {INT, PTR, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_rt_sigprocmask, INT, "rt_sigprocmask", {INT, PTR, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_rt_sigreturn, INT, "rt_sigreturn", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_ioctl, INT, "ioctl", {INT, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_pread64, INT, "pread64", {INT, STR, INT, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_pwrite64, INT, "pwrite64", {INT, STR, INT, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_readv, INT, "readv", {INT, PTR, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_writev, INT, "writev", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_access, INT, "access", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_pipe, INT, "pipe", {PTR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_select, INT, "select", {INT, PTR, PTR, PTR, PTR, UNDEFINED}, 5},
    {SYS_sched_yield, INT, "sched_yield", {UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 0},
    {SYS_mremap, INT, "mremap", {INT, INT, INT, INT, INT, UNDEFINED}, 5},
    {SYS_msync, INT, "msync", {INT, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_mincore, INT, "mincore", {INT, INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_madvise, INT, "madvise", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_shmget, INT, "shmget", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_shmat, INT, "shmat", {INT, STR, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_shmctl, INT, "shmctl", {INT, INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_dup, INT, "dup", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_dup2, INT, "dup2", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_pause, INT, "pause", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_nanosleep, INT, "nanosleep", {PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getitimer, INT, "getitimer", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_alarm, INT, "alarm", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_setitimer, INT, "setitimer", {INT, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getpid, INT, "getpid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_sendfile, INT, "sendfile", {INT, INT, PTR, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_socket, INT, "socket", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_connect, INT, "connect", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_accept, INT, "accept", {INT, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_sendto, INT, "sendto", {INT, PTR, INT, INT, PTR, INT}, 6},
    {SYS_recvfrom, INT, "recvfrom", {INT, PTR, INT, INT, PTR, PTR}, 6},
    {SYS_sendmsg, INT, "sendmsg", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_recvmsg, INT, "recvmsg", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_shutdown, INT, "shutdown", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_bind, INT, "bind", {INT, PTR, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_listen, INT, "listen", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_getsockname, INT, "getsockname", {INT, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getpeername, INT, "getpeername", {INT, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_socketpair, INT, "socketpair", {INT, INT, INT, PTR, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_setsockopt, INT, "setsockopt", {INT, INT, INT, STR, INT, UNDEFINED},
        5},
    {SYS_getsockopt, INT, "getsockopt", {INT, INT, INT, STR, PTR, UNDEFINED},
        5},
    {SYS_clone, INT, "clone", {INT, INT, PTR, PTR, INT, UNDEFINED}, 5},
    {SYS_fork, INT, "fork", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_vfork, INT, "vfork", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_execve, INT, "execve", {STR, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_exit, INT, "exit", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_wait4, INT, "wait4", {INT, PTR, INT, PTR, UNDEFINED, UNDEFINED}, 4},
    {SYS_kill, INT, "kill", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_uname, INT, "uname", {PTR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_semget, INT, "semget", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_semop, INT, "semop", {INT, PTR, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_semctl, INT, "semctl", {INT, INT, INT, INT, UNDEFINED, UNDEFINED}, 4},
    {SYS_shmdt, INT, "shmdt", {STR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_msgget, INT, "msgget", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_msgsnd, INT, "msgsnd", {INT, PTR, INT, INT, UNDEFINED, UNDEFINED}, 4},
    {SYS_msgrcv, INT, "msgrcv", {INT, PTR, INT, INT, INT, UNDEFINED}, 5},
    {SYS_msgctl, INT, "msgctl", {INT, INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_fcntl, INT, "fcntl", {INT, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_flock, INT, "flock", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_fsync, INT, "fsync", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_fdatasync, INT, "fdatasync", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_truncate, INT, "truncate", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_ftruncate, INT, "ftruncate", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getdents, INT, "getdents", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getcwd, INT, "getcwd", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_chdir, INT, "chdir", {STR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_fchdir, INT, "fchdir", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_rename, INT, "rename", {STR, STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_mkdir, INT, "mkdir", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_rmdir, INT, "rmdir", {STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_creat, INT, "creat", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_link, INT, "link", {STR, STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_unlink, INT, "unlink", {STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_symlink, INT, "symlink", {STR, STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_readlink, INT, "readlink", {STR, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_chmod, INT, "chmod", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_fchmod, INT, "fchmod", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_chown, INT, "chown", {STR, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_fchown, INT, "fchown", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_lchown, INT, "lchown", {STR, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_umask, INT, "umask", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_gettimeofday, INT, "gettimeofday", {PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getrlimit, INT, "getrlimit", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getrusage, INT, "getrusage", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_sysinfo, INT, "sysinfo", {PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_times, INT, "times", {PTR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_ptrace, INT, "ptrace", {INT, INT, INT, INT, UNDEFINED, UNDEFINED}, 4},
    {SYS_getuid, INT, "getuid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_syslog, INT, "syslog", {INT, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getgid, INT, "getgid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_setuid, INT, "setuid", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_setgid, INT, "setgid", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_geteuid, INT, "geteuid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_getegid, INT, "getegid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_setpgid, INT, "setpgid", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getppid, INT, "getppid", {UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 0},
    {SYS_getpgrp, INT, "getpgrp", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_setsid, INT, "setsid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_setreuid, INT, "setreuid", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_setregid, INT, "setregid", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getgroups, INT, "getgroups", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_setgroups, INT, "setgroups", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_setresuid, INT, "setresuid", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getresuid, INT, "getresuid", {PTR, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_setresgid, INT, "setresgid", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getresgid, INT, "getresgid", {PTR, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getpgid, INT, "getpgid", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_setfsuid, INT, "setfsuid", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_setfsgid, INT, "setfsgid", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_getsid, INT, "getsid", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_capget, INT, "capget", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_capset, INT, "capset", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_rt_sigpending, INT, "rt_sigpending", {PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_rt_sigtimedwait, INT, "rt_sigtimedwait", {PTR, PTR, PTR, INT,
        UNDEFINED, UNDEFINED}, 4},
    {SYS_rt_sigqueueinfo, INT, "rt_sigqueueinfo", {INT, INT, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_rt_sigsuspend, INT, "rt_sigsuspend", {PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_sigaltstack, INT, "sigaltstack", {PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_utime, INT, "utime", {STR, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_mknod, INT, "mknod", {STR, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_uselib, INT, "uselib", {STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_personality, INT, "personality", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_ustat, INT, "ustat", {INT, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_statfs, INT, "statfs", {STR, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_fstatfs, INT, "fstatfs", {INT, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_sysfs, INT, "sysfs", {INT, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_getpriority, INT, "getpriority", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_setpriority, INT, "setpriority", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_sched_setparam, INT, "sched_setparam", {INT, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_sched_getparam, INT, "sched_getparam", {INT, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_sched_setscheduler, INT, "sched_setscheduler", {INT, INT, PTR,
        UNDEFINED, UNDEFINED, UNDEFINED}, 3},
    {SYS_sched_getscheduler, INT, "sched_getscheduler", {INT, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_sched_get_priority_max, INT, "sched_get_priority_max", {INT,
        UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_sched_get_priority_min, INT, "sched_get_priority_min", {INT,
        UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_sched_rr_get_interval, INT, "sched_rr_get_interval", {INT, PTR,
        UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_mlock, INT, "mlock", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_munlock, INT, "munlock", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_mlockall, INT, "mlockall", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_munlockall, INT, "munlockall", {UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 0},
    {SYS_vhangup, INT, "vhangup", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_modify_ldt, INT, "modify_ldt", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_pivot_root, INT, "pivot_root", {STR, STR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS__sysctl, INT, "_sysctl", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_prctl, INT, "prctl", {INT, INT, INT, INT, INT, UNDEFINED}, 5},
    {SYS_arch_prctl, INT, "arch_prctl", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_adjtimex, INT, "adjtimex", {PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_setrlimit, INT, "setrlimit", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_chroot, INT, "chroot", {STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_sync, INT, "sync", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_acct, INT, "acct", {STR, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_settimeofday, INT, "settimeofday", {PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_mount, INT, "mount", {STR, STR, STR, INT, PTR, UNDEFINED}, 5},
    {SYS_umount2, INT, "umount2", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_swapon, INT, "swapon", {STR, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_swapoff, INT, "swapoff", {STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_reboot, INT, "reboot", {INT, INT, INT, PTR, UNDEFINED, UNDEFINED}, 4},
    {SYS_sethostname, INT, "sethostname", {STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_setdomainname, INT, "setdomainname", {STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_iopl, INT, "iopl", {INT, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 1},
    {SYS_ioperm, INT, "ioperm", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_create_module, INT, "create_module", {PTR, PTR, PTR, PTR, PTR, PTR},
        6},
    {SYS_init_module, INT, "init_module", {PTR, INT, STR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_delete_module, INT, "delete_module", {STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_get_kernel_syms, INT, "get_kernel_syms", {PTR, PTR, PTR, PTR, PTR,
        PTR}, 6},
    {SYS_query_module, INT, "query_module", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_quotactl, INT, "quotactl", {INT, STR, INT, PTR, UNDEFINED, UNDEFINED},
        4},
    {SYS_nfsservctl, INT, "nfsservctl", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_getpmsg, INT, "getpmsg", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_putpmsg, INT, "putpmsg", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_afs_syscall, INT, "afs_syscall", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_tuxcall, INT, "tuxcall", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_security, INT, "security", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_gettid, INT, "gettid", {UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 0},
    {SYS_readahead, INT, "readahead", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_setxattr, INT, "setxattr", {STR, STR, PTR, INT, INT, UNDEFINED}, 5},
    {SYS_lsetxattr, INT, "lsetxattr", {STR, STR, PTR, INT, INT, UNDEFINED}, 5},
    {SYS_fsetxattr, INT, "fsetxattr", {INT, STR, PTR, INT, INT, UNDEFINED}, 5},
    {SYS_getxattr, INT, "getxattr", {STR, STR, PTR, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_lgetxattr, INT, "lgetxattr", {STR, STR, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_fgetxattr, INT, "fgetxattr", {INT, STR, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_listxattr, INT, "listxattr", {STR, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_llistxattr, INT, "llistxattr", {STR, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_flistxattr, INT, "flistxattr", {INT, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_removexattr, INT, "removexattr", {STR, STR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_lremovexattr, INT, "lremovexattr", {STR, STR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_fremovexattr, INT, "fremovexattr", {INT, STR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_tkill, INT, "tkill", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_time, INT, "time", {PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_futex, INT, "futex", {PTR, INT, INT, PTR, PTR, INT}, 6},
    {SYS_sched_setaffinity, INT, "sched_setaffinity", {INT, INT, PTR,
        UNDEFINED, UNDEFINED, UNDEFINED}, 3},
    {SYS_sched_getaffinity, INT, "sched_getaffinity", {INT, INT, PTR,
        UNDEFINED, UNDEFINED, UNDEFINED}, 3},
    {SYS_set_thread_area, INT, "set_thread_area", {PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_io_setup, INT, "io_setup", {INT, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_io_destroy, INT, "io_destroy", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_io_getevents, INT, "io_getevents", {INT, INT, INT, PTR, PTR,
        UNDEFINED}, 5},
    {SYS_io_submit, INT, "io_submit", {INT, INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_io_cancel, INT, "io_cancel", {INT, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_get_thread_area, INT, "get_thread_area", {PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_lookup_dcookie, INT, "lookup_dcookie", {INT, STR, INT, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_epoll_create, INT, "epoll_create", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_epoll_ctl_old, INT, "epoll_ctl_old", {PTR, PTR, PTR, PTR, PTR, PTR},
        6},
    {SYS_epoll_wait_old, INT, "epoll_wait_old", {PTR, PTR, PTR, PTR, PTR, PTR},
        6},
    {SYS_remap_file_pages, INT, "remap_file_pages", {INT, INT, INT, INT, INT,
        UNDEFINED}, 5},
    {SYS_getdents64, INT, "getdents64", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_set_tid_address, INT, "set_tid_address", {PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_restart_syscall, INT, "restart_syscall", {UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED}, 0},
    {SYS_semtimedop, INT, "semtimedop", {INT, PTR, INT, PTR, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_fadvise64, INT, "fadvise64", {INT, INT, INT, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_timer_create, INT, "timer_create", {INT, PTR, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_timer_settime, INT, "timer_settime", {INT, INT, PTR, PTR, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_timer_gettime, INT, "timer_gettime", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_timer_getoverrun, INT, "timer_getoverrun", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_timer_delete, INT, "timer_delete", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_clock_settime, INT, "clock_settime", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_clock_gettime, INT, "clock_gettime", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_clock_getres, INT, "clock_getres", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_clock_nanosleep, INT, "clock_nanosleep", {INT, INT, PTR, PTR,
        UNDEFINED, UNDEFINED}, 4},
    {SYS_exit_group, INT, "exit_group", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_epoll_wait, INT, "epoll_wait", {INT, PTR, INT, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_epoll_ctl, INT, "epoll_ctl", {INT, INT, INT, PTR, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_tgkill, INT, "tgkill", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_utimes, INT, "utimes", {STR, PTR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_vserver, INT, "vserver", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_mbind, INT, "mbind", {INT, INT, INT, PTR, INT, INT}, 6},
    {SYS_set_mempolicy, INT, "set_mempolicy", {INT, PTR, INT, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_get_mempolicy, INT, "get_mempolicy", {PTR, PTR, INT, INT, INT,
        UNDEFINED}, 5},
    {SYS_mq_open, INT, "mq_open", {STR, INT, INT, PTR, UNDEFINED, UNDEFINED},
        4},
    {SYS_mq_unlink, INT, "mq_unlink", {STR, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_mq_timedsend, INT, "mq_timedsend", {INT, STR, INT, INT, PTR,
        UNDEFINED}, 5},
    {SYS_mq_timedreceive, INT, "mq_timedreceive", {INT, STR, INT, PTR, PTR,
        UNDEFINED}, 5},
    {SYS_mq_notify, INT, "mq_notify", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_mq_getsetattr, INT, "mq_getsetattr", {INT, PTR, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_kexec_load, INT, "kexec_load", {INT, INT, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_waitid, INT, "waitid", {INT, INT, PTR, INT, PTR, UNDEFINED}, 5},
    {SYS_add_key, INT, "add_key", {STR, STR, PTR, INT, INT, UNDEFINED}, 5},
    {SYS_request_key, INT, "request_key", {STR, STR, STR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_keyctl, INT, "keyctl", {INT, INT, INT, INT, INT, UNDEFINED}, 5},
    {SYS_ioprio_set, INT, "ioprio_set", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_ioprio_get, INT, "ioprio_get", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_inotify_init, INT, "inotify_init", {UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 0},
    {SYS_inotify_add_watch, INT, "inotify_add_watch", {INT, STR, INT,
        UNDEFINED, UNDEFINED, UNDEFINED}, 3},
    {SYS_inotify_rm_watch, INT, "inotify_rm_watch", {INT, INT, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_migrate_pages, INT, "migrate_pages", {INT, INT, PTR, PTR, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_openat, INT, "openat", {INT, STR, INT, INT, UNDEFINED, UNDEFINED}, 4},
    {SYS_mkdirat, INT, "mkdirat", {INT, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_mknodat, INT, "mknodat", {INT, STR, INT, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_fchownat, INT, "fchownat", {INT, STR, INT, INT, INT, UNDEFINED}, 5},
    {SYS_futimesat, INT, "futimesat", {INT, STR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_newfstatat, INT, "newfstatat", {INT, STR, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_unlinkat, INT, "unlinkat", {INT, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_renameat, INT, "renameat", {INT, STR, INT, STR, UNDEFINED, UNDEFINED},
        4},
    {SYS_linkat, INT, "linkat", {INT, STR, INT, STR, INT, UNDEFINED}, 5},
    {SYS_symlinkat, INT, "symlinkat", {STR, INT, STR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_readlinkat, INT, "readlinkat", {INT, STR, STR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_fchmodat, INT, "fchmodat", {INT, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_faccessat, INT, "faccessat", {INT, STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_pselect6, INT, "pselect6", {INT, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_ppoll, INT, "ppoll", {PTR, INT, PTR, PTR, INT, UNDEFINED}, 5},
    {SYS_unshare, INT, "unshare", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_set_robust_list, INT, "set_robust_list", {PTR, INT, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_get_robust_list, INT, "get_robust_list", {INT, PTR, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_splice, INT, "splice", {INT, PTR, INT, PTR, INT, INT}, 6},
    {SYS_tee, INT, "tee", {INT, INT, INT, INT, UNDEFINED, UNDEFINED}, 4},
    {SYS_sync_file_range, INT, "sync_file_range", {INT, INT, INT, INT,
        UNDEFINED, UNDEFINED}, 4},
    {SYS_vmsplice, INT, "vmsplice", {INT, PTR, INT, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_move_pages, INT, "move_pages", {INT, INT, PTR, PTR, PTR, INT}, 6},
    {SYS_utimensat, INT, "utimensat", {INT, STR, PTR, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_epoll_pwait, INT, "epoll_pwait", {INT, PTR, INT, INT, PTR, INT}, 6},
    {SYS_signalfd, INT, "signalfd", {INT, PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_timerfd_create, INT, "timerfd_create", {INT, INT, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_eventfd, INT, "eventfd", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_fallocate, INT, "fallocate", {INT, INT, INT, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_timerfd_settime, INT, "timerfd_settime", {INT, INT, PTR, PTR,
        UNDEFINED, UNDEFINED}, 4},
    {SYS_timerfd_gettime, INT, "timerfd_gettime", {INT, PTR, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 2},
    {SYS_accept4, INT, "accept4", {INT, PTR, PTR, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_signalfd4, INT, "signalfd4", {INT, PTR, INT, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_eventfd2, INT, "eventfd2", {INT, INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED}, 2},
    {SYS_epoll_create, INT, "epoll_create1", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_dup3, INT, "dup3", {INT, INT, INT, UNDEFINED, UNDEFINED, UNDEFINED},
        3},
    {SYS_pipe2, INT, "pipe2", {PTR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_inotify_init1, INT, "inotify_init1", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_preadv, INT, "preadv", {INT, PTR, INT, INT, INT, UNDEFINED}, 5},
    {SYS_pwritev, INT, "pwritev", {INT, PTR, INT, INT, INT, UNDEFINED}, 5},
    {SYS_rt_tgsigqueueinfo, INT, "rt_tgsigqueueinfo", {INT, INT, INT, PTR,
        UNDEFINED, UNDEFINED}, 4},
    {SYS_perf_event_open, INT, "perf_event_open", {PTR, INT, INT, INT, INT,
        UNDEFINED}, 5},
    {SYS_recvmmsg, INT, "recvmmsg", {INT, PTR, INT, INT, PTR, UNDEFINED}, 5},
    {SYS_fanotify_init, INT, "fanotify_init", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_fanotify_mark, INT, "fanotify_mark", {INT, INT, INT, INT, STR,
        UNDEFINED}, 5},
    {SYS_prlimit64, INT, "prlimit64", {INT, INT, PTR, PTR, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_name_to_handle_at, INT, "name_to_handle_at", {INT, STR, PTR, PTR, INT,
        UNDEFINED}, 5},
    {SYS_open_by_handle_at, INT, "open_by_handle_at", {INT, PTR, INT, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_clock_adjtime, INT, "clock_adjtime", {INT, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_syncfs, INT, "syncfs", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1},
    {SYS_sendmmsg, INT, "sendmmsg", {INT, PTR, INT, INT, UNDEFINED, UNDEFINED},
        4},
    {SYS_setns, INT, "setns", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_getcpu, INT, "getcpu", {PTR, PTR, PTR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_process_vm_readv, INT, "process_vm_readv", {INT, PTR, INT, PTR, INT,
        INT}, 6},
    {SYS_process_vm_writev, INT, "process_vm_writev", {INT, PTR, INT, PTR, INT,
        INT}, 6},
    {SYS_kcmp, INT, "kcmp", {INT, INT, INT, INT, INT, UNDEFINED}, 5},
    {SYS_finit_module, INT, "finit_module", {INT, STR, INT, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_sched_setattr, INT, "sched_setattr", {INT, PTR, INT, UNDEFINED,
        UNDEFINED, UNDEFINED}, 3},
    {SYS_sched_getattr, INT, "sched_getattr", {INT, PTR, INT, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_renameat2, INT, "renameat2", {INT, STR, INT, STR, INT, UNDEFINED}, 5},
    {SYS_seccomp, INT, "seccomp", {INT, INT, STR, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_getrandom, INT, "getrandom", {PTR, PTR, PTR, PTR, PTR, PTR}, 6},
    {SYS_memfd_create, INT, "memfd_create", {STR, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_kexec_file_load, INT, "kexec_file_load", {INT, INT, INT, STR, INT,
        UNDEFINED}, 5},
    {SYS_bpf, INT, "bpf", {INT, PTR, INT, UNDEFINED, UNDEFINED, UNDEFINED}, 3},
    {SYS_execveat, INT, "execveat", {INT, STR, PTR, PTR, INT, UNDEFINED}, 5},
    {SYS_userfaultfd, INT, "userfaultfd", {INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED, UNDEFINED}, 1},
    {SYS_membarrier, INT, "membarrier", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_mlock2, INT, "mlock2", {INT, INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED}, 3},
    {SYS_copy_file_range, INT, "copy_file_range", {INT, PTR, INT, PTR, INT,
        INT}, 6},
    {SYS_preadv2, INT, "preadv2", {INT, PTR, INT, INT, INT, INT}, 6},
    {SYS_pwritev2, INT, "pwritev2", {INT, PTR, INT, INT, INT, INT}, 6},
    {SYS_pkey_mprotect, INT, "pkey_mprotect", {INT, INT, INT, INT, UNDEFINED,
        UNDEFINED}, 4},
    {SYS_pkey_alloc, INT, "pkey_alloc", {INT, INT, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 2},
    {SYS_pkey_free, INT, "pkey_free", {INT, UNDEFINED, UNDEFINED, UNDEFINED,
        UNDEFINED, UNDEFINED}, 1}
};

#endif /* !ftrace_LIST_H_ */
